"""Reviewed RP2040 minimal circuit recipe.

Pin roles and required TESTEN/decoupling/BOOTSEL connections follow Raspberry Pi
RP2040 Datasheet section 2.1 and Hardware Design with RP2040 sections 2-4:
https://datasheets.raspberrypi.com/rp2040/rp2040-datasheet.pdf
https://datasheets.raspberrypi.com/rp2040/hardware-design-with-rp2040.pdf
"""

from .models import RecipeComponentGroup as Group
from .models import (
    RecipeDefinition,
    RecipeEdgeSpec,
    RecipeNoConnectSpec as NoConnect,
    RecipePinSpec as Pin,
)

RP2040_MINIMAL = RecipeDefinition(
    recipe="rp2040-minimal@1",
    required_sheet_roles=("mcu", "io"),
    parameter_defaults={
        "usb": True,
        "programming": "bootsel+swd",
        "flash_mbit": 16,
        "gpio_exposed": 30,
    },
    allowed_parameters={
        "usb": (True,),
        "programming": ("bootsel+swd",),
        "flash_mbit": (16,),
        "gpio_exposed": (30,),
    },
    parts=(
        Group(
            role="mcu",
            reference_prefix="U",
            value="RP2040",
            symbol="MCU_RaspberryPi:RP2040",
            footprint="Package_DFN_QFN:QFN-56-1EP_7x7mm_P0.4mm_EP3.2x3.2mm",
            sheet_role="mcu",
        ),
        Group(
            role="flash",
            reference_prefix="U",
            value="W25Q16JVSS",
            symbol="Memory_Flash:W25Q16JVSS",
            footprint="Package_SO:SOIC-8_3.9x4.9mm_P1.27mm",
            sheet_role="mcu",
        ),
        Group(
            role="crystal",
            reference_prefix="Y",
            value="12MHz",
            symbol="Device:Crystal",
            footprint="Crystal:Crystal_SMD_3225-4Pin_3.2x2.5mm",
            sheet_role="mcu",
        ),
        Group(
            role="xout_resistor",
            reference_prefix="R",
            value="1k",
            symbol="Device:R",
            footprint="Resistor_SMD:R_0402_1005Metric",
            sheet_role="mcu",
        ),
        Group(
            role="bootsel",
            reference_prefix="SW",
            value="BOOTSEL",
            symbol="Switch:SW_Push",
            footprint="Button_Switch_SMD:SW_Push_1P1T_NO_E-Switch_TL3301NxxxxxG",
            sheet_role="mcu",
        ),
        Group(
            role="swd",
            reference_prefix="J",
            value="SWD 1x4",
            symbol="Connector_Generic:Conn_01x04",
            footprint="Connector_PinHeader_2.54mm:PinHeader_1x04_P2.54mm_Vertical",
            sheet_role="mcu",
        ),
        Group(
            role="io_decoupling",
            reference_prefix="C",
            quantity=8,
            value="100nF",
            symbol="Device:C",
            footprint="Capacitor_SMD:C_0402_1005Metric",
            sheet_role="mcu",
        ),
        Group(
            role="dvdd_decoupling",
            reference_prefix="C",
            value="1uF",
            symbol="Device:C",
            footprint="Capacitor_SMD:C_0402_1005Metric",
            sheet_role="mcu",
        ),
        Group(
            role="bulk_decoupling",
            reference_prefix="C",
            value="10uF",
            symbol="Device:C",
            footprint="Capacitor_SMD:C_0805_2012Metric",
            sheet_role="mcu",
        ),
        Group(
            role="xin_cap",
            reference_prefix="C",
            value="15pF",
            symbol="Device:C",
            footprint="Capacitor_SMD:C_0402_1005Metric",
            sheet_role="mcu",
        ),
        Group(
            role="xout_cap",
            reference_prefix="C",
            value="15pF",
            symbol="Device:C",
            footprint="Capacitor_SMD:C_0402_1005Metric",
            sheet_role="mcu",
        ),
        Group(
            role="cast_left",
            reference_prefix="TP",
            quantity=17,
            value="Castellated pad",
            symbol="castellated-pad-2p54:Conn_01x01",
            footprint="castellated-pad-2p54:Castellated_Pad_2.54mm",
            sheet_role="io",
            assembly=False,
        ),
        Group(
            role="cast_right",
            reference_prefix="TP",
            quantity=17,
            value="Castellated pad",
            symbol="castellated-pad-2p54:Conn_01x01",
            footprint="castellated-pad-2p54:Castellated_Pad_2.54mm",
            sheet_role="io",
            assembly=False,
        ),
    ),
    pins=(
        Pin(role="mcu", pin="19", net="GND"),
        Pin(role="mcu", pin="57", net="GND"),
        Pin(role="mcu", pin="56", net="QSPI_CS"),
        Pin(role="mcu", pin="52", net="QSPI_SCLK"),
        Pin(role="mcu", pin="53", net="QSPI_SD0"),
        Pin(role="mcu", pin="55", net="QSPI_SD1"),
        Pin(role="mcu", pin="54", net="QSPI_SD2"),
        Pin(role="mcu", pin="51", net="QSPI_SD3"),
        Pin(role="mcu", pin="20", net="XIN"),
        Pin(role="mcu", pin="21", net="XOUT_RAW"),
        Pin(role="mcu", pin="24", net="SWCLK"),
        Pin(role="mcu", pin="25", net="SWDIO"),
        Pin(role="mcu", pin="46", net="USB_DM"),
        Pin(role="mcu", pin="47", net="USB_DP"),
        Pin(role="mcu", pin="48", net="3V3"),
        Pin(role="mcu", pin="43", net="3V3"),
        Pin(role="mcu", pin="1", net="3V3"),
        Pin(role="mcu", pin="10", net="3V3"),
        Pin(role="mcu", pin="22", net="3V3"),
        Pin(role="mcu", pin="33", net="3V3"),
        Pin(role="mcu", pin="42", net="3V3"),
        Pin(role="mcu", pin="49", net="3V3"),
        Pin(role="mcu", pin="44", net="3V3"),
        Pin(role="mcu", pin="45", net="DVDD_1V1"),
        Pin(role="mcu", pin="23", net="DVDD_1V1"),
        Pin(role="mcu", pin="50", net="DVDD_1V1"),
        Pin(role="flash", pin="1", net="QSPI_CS"),
        Pin(role="flash", pin="2", net="QSPI_SD1"),
        Pin(role="flash", pin="3", net="QSPI_SD2"),
        Pin(role="flash", pin="4", net="GND"),
        Pin(role="flash", pin="5", net="QSPI_SD0"),
        Pin(role="flash", pin="6", net="QSPI_SCLK"),
        Pin(role="flash", pin="7", net="QSPI_SD3"),
        Pin(role="flash", pin="8", net="3V3"),
        Pin(role="bootsel", pin="1", net="QSPI_CS"),
        Pin(role="bootsel", pin="2", net="GND"),
        Pin(role="swd", pin="1", net="3V3"),
        Pin(role="swd", pin="2", net="SWDIO"),
        Pin(role="swd", pin="3", net="GND"),
        Pin(role="swd", pin="4", net="SWCLK"),
        Pin(role="crystal", pin="1", net="XIN"),
        Pin(role="crystal", pin="2", net="XOUT"),
        Pin(role="xout_resistor", pin="1", net="XOUT_RAW"),
        Pin(role="xout_resistor", pin="2", net="XOUT"),
        Pin(role="dvdd_decoupling", pin="1", net="DVDD_1V1"),
        Pin(role="dvdd_decoupling", pin="2", net="GND"),
        Pin(role="bulk_decoupling", pin="1", net="3V3"),
        Pin(role="bulk_decoupling", pin="2", net="GND"),
        Pin(role="xin_cap", pin="1", net="XIN"),
        Pin(role="xin_cap", pin="2", net="GND"),
        Pin(role="xout_cap", pin="1", net="XOUT"),
        Pin(role="xout_cap", pin="2", net="GND"),
        *(
            Pin(role="io_decoupling", index=index, pin=pin, net=net)
            for index in range(8)
            for pin, net in (("1", "3V3"), ("2", "GND"))
        ),
        *(
            Pin(role="mcu", pin=pin, net=f"GPIO{index}")
            for index, pin in enumerate(
                (
                    "2",
                    "3",
                    "4",
                    "5",
                    "6",
                    "7",
                    "8",
                    "9",
                    "11",
                    "12",
                    "13",
                    "14",
                    "15",
                    "16",
                    "17",
                    "18",
                    "27",
                    "28",
                    "29",
                    "30",
                    "31",
                    "32",
                    "34",
                    "35",
                    "36",
                    "37",
                    "38",
                    "39",
                    "40",
                    "41",
                )
            )
        ),
        Pin(role="cast_left", index=0, pin="1", net="3V3"),
        Pin(role="cast_left", index=1, pin="1", net="GND"),
        *(
            Pin(role="cast_left", index=index + 2, pin="1", net=f"GPIO{index}")
            for index in range(15)
        ),
        *(
            Pin(role="cast_right", index=index, pin="1", net=f"GPIO{index + 15}")
            for index in range(15)
        ),
        Pin(role="cast_right", index=15, pin="1", net="USB_DM"),
        Pin(role="cast_right", index=16, pin="1", net="USB_DP"),
    ),
    no_connects=(NoConnect(role="mcu", pin="26"),),
    edges=(
        RecipeEdgeSpec(role="cast_left", side="left", pitch_mm=2.54),
        RecipeEdgeSpec(role="cast_right", side="right", pitch_mm=2.54),
    ),
)
